#!/bin/bash

# Handle if on cse machine
command -v spim >/dev/null || {
  1521 autotest cellular
  exit
}

tests=('5\n30\n0' '6\n3\n0' '5\n31\n1' '6\n29\n1' '60\n32\n0' '60\n33\n1' '60\n34\n2'
'60\n35\n10' '60\n7\n10' '80\n12\n7' '42\n42\n42' '72\n255\n-1' '15\n155\n-10'
'51\n177\n-50' '300\n11\n11' '11\n-310\n11' '11\n11\n-320')

# Make dir for outputs
[ -d "test" ] || mkdir test

make

for i in ${!tests[@]}; do
  testin="${tests[$i]}"
  echo "${test}" | ./cellular > test/${i}.exp
  echo "${test}" | spim -f cellular.s | tail -n +2 > test/${i}.out

  echo -ne "Test $i: ($(echo -ne $testin | tr "\n" " ")) \t"
  if ! diff "test/$i.exp" "test/$i.out" >/dev/null; then
    echo -e "\033[31m failed \033[0m"
  else
    echo -e "\033[32m passed \033[0m"
  fi
done
